---
# This playbook will install mysql and create db user and give permissions.

- name: Install Mysql package
  package:
    name: "{{ item }}"
    state: present
  with_items:
   - mysql-server
   - python3-mysqldb
   - python3-selinux
   - python3-semanage

- name: Check SELinux status
  command: getenforce
  register: selinux_status
  ignore_errors: true

- name: Configure SELinux to start mysql on any port
  seboolean:
    name: mysql_connect_any
    state: true
    persistent: yes
  when: selinux_status.stdout == "Enforcing"

- name: Create Mysql configuration file
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf
  notify:
  - restart mysql

- name: Start Mysql Service
  service:
    name: mysqld
    state: started
    enabled: yes

- name: insert iptables rule
  lineinfile:
    dest: /etc/sysconfig/iptables
    state: present
    regexp: "{{ mysql_port }}"
    insertafter: "^:OUTPUT "
    line: "-A INPUT -p tcp  --dport {{ mysql_port }} -j  ACCEPT"
  notify: restart iptables

- name: Create Application Database
  mysql_db:
    name: "{{ dbname }}"
    state: present

- name: Create Application DB User
  mysql_user:
    name: "{{ dbuser }}"
    password: "{{ upassword }}"
    priv: "*.*:ALL"
    host: '%'
    state: present
