---
# This playbook will create a SQLite database and user.
- name: Ensure sqlite3 is installed
  apt:
    name: sqlite3
    state: present

- name: Ensure database directory exists
  file:
    path: "/root/database"
    state: directory
    mode: '0755'

- name: Check if SQLite database exists
  stat:
    path: "/root/database/{{ dbname }}.db"
  register: db

- name: Create SQLite database
  command: sqlite3 /root/database/{{ dbname }}.db ".databases"
  when: db.stat.exists == False

- name: Create Application DB User
  blockinfile:
    path: /root/database/{{ dbname }}.db
    block: |
      CREATE USER '{{ dbuser }}' WITH PASSWORD '{{ upassword }}';
      GRANT ALL PRIVILEGES ON DATABASE '{{ dbname }}' TO '{{ dbuser }}';
  when: db.stat.exists == False