---
# These tasks install http and the php modules.

- name: Install http and php etc
  package:
    name: "{{ item }}"
    state: present
  with_items:
   - apache2
   - php
   - php-mysql
   - git
   - python3-semanage
   - python3-selinux
   - policycoreutils

- name: install iptables
  package:
    name: iptables-persistent
    state: present

- name: insert iptables rule for httpd
  lineinfile:
    dest: /etc/sysconfig/iptables
    create: yes
    state: present
    regexp: "{{ httpd_port }}"
    insertafter: "^:OUTPUT "
    line: "-A INPUT -p tcp  --dport {{ httpd_port }} -j  ACCEPT"
  notify: restart iptables

- name: http service state
  service:
    name: apache2
    state: started
    enabled: yes

- name: Check SELinux status
  command: getenforce
  register: selinux_status
  ignore_errors: true

- name: Configure SELinux to allow httpd to connect to remote database
  seboolean:
    name: apache2_can_network_connect_db
    state: true
    persistent: yes
  when: selinux_status.stdout == "Enforcing"
