- name: Install chrony
  package:
    name: chrony
    state: present
  tags: chrony

- name: Configure chrony file
  template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
  tags: chrony
  notify: restart chrony

- name: Start the chrony service
  service:
    name: chrony
    state: started
    enabled: yes
  tags: chrony